name: spajam2022_kyoto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  liquid_swipe: ^3.0.0
  card_swiper: ^2.0.4
  audioplayers: ^0.19.1
  firebase_core: ^1.23.0
  flutter_stripe: 4.0.0
  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
